spring:
  datasource:
    name: login_regi  #数据库名
    url: jdbc:mysql://localhost:3306/login_regi?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC #url
    username: root  #用户名
    password: yangjing  #密码
    driver-class-name: com.mysql.cj.jdbc.Driver  #数据库链接驱动
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    #这是你的邮箱
    username: 1685757000@qq.com
    #这是你QQ邮箱内第三方POP3/SMTP服务密码需要开启，在QQ邮箱-设置-账户
    password: mvwcewgyjttidihj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
mybatis:
  mapper-locations: classpath:mapper/*.xml  #配置映射文件
  type-aliases-package: com.example.loginspr.bean #配置实体类
server:
  port: 8081